version: '3.7'
services:
  unifi-db:
    image: docker.io/mongo:7.0.15
    container_name: unifi-db
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=grumpfrumper
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
      - MONGO_AUTHSOURCE= #optional
    volumes:
      - ./config:/config
    ports:
      - 8443
      - 3478/udp
      - 10001/udp
      - 8080
      - 1900/udp #optional
      - 8843 #optional
      - 8880 #optional
      - 6789 #optional
      - 5514/udp #optional
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi_insecure.entrypoints=web"
      - "traefik.http.routers.unifi_insecure.rule=Host(`unifiapp.teletraan.one`)"
      - "traefik.http.routers.unifi.entrypoints=web-secure"
      - "traefik.http.routers.unifi.rule=Host(`unifiapp.teletraan.one`)"
      - "traefik.http.routers.unifi.tls.certresolver=letsencrypt"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
    networks:
      - traefik-proxy
      - default
networks:
  traefik-proxy:
    external: true  


